--Emily Zeng
--CIS 310-01
--A7
--Cases 103-125 on pgs. 331-339

--103
SELECT	MOVIE_TITLE, MOVIE_YEAR, MOVIE_GENRE
FROM	MOVIE

--104
SELECT	MOVIE_YEAR, MOVIE_TITLE, MOVIE_COST
FROM	MOVIE
ORDER BY	MOVIE_YEAR DESC 

--105
SELECT	MOVIE_TITLE, MOVIE_YEAR, MOVIE_GENRE
FROM	MOVIE
ORDER BY	MOVIE_GENRE ASC, MOVIE_YEAR DESC

--106
SELECT	MOVIE_NUM, MOVIE_TITLE, PRICE_CODE
FROM	MOVIE
WHERE	MOVIE_TITLE LIKE 'R%'

--107
SELECT	MOVIE_TITLE, MOVIE_YEAR, MOVIE_COST
FROM	MOVIE
WHERE	MOVIE_TITLE LIKE '%HOPE%'
ORDER BY	MOVIE_TITLE ASC

--108
SELECT	MOVIE_TITLE, MOVIE_YEAR, MOVIE_GENRE
FROM	MOVIE
WHERE	MOVIE_GENRE = 'ACTION'

--109
SELECT	MOVIE_NUM, MOVIE_TITLE, MOVIE_COST
FROM	MOVIE
WHERE	MOVIE_COST > 40

--110
SELECT	MOVIE_NUM, MOVIE_TITLE, MOVIE_COST, MOVIE_GENRE
FROM	MOVIE
WHERE	MOVIE_GENRE IN ('ACTION','COMEDY') AND
		MOVIE_COST < 50
ORDER BY	MOVIE_GENRE 

--111
SELECT	MEM_NUM, MEM_FNAME, MEM_LNAME, MEM_STREET, MEM_STATE, MEM_BALANCE
FROM	MEMBERSHIP
WHERE	MEM_STATE = 'TN' AND 
		MEM_BALANCE < 5 AND 
		MEM_STREET LIKE '%AVENUE'

--112
SELECT	MOVIE_GENRE, COUNT(*) AS [NUMBER OF MOVIES]
FROM	MOVIE
GROUP BY MOVIE_GENRE

--113
SELECT	AVG(MOVIE_COST) AS [AVERAGE MOVIE COST]
FROM	MOVIE

--114
SELECT	MOVIE_GENRE, AVG(MOVIE_COST) AS [AVERAGE MOVIE COST]
FROM	MOVIE
GROUP BY	MOVIE_GENRE

--115
SELECT	MOVIE_TITLE, MOVIE_GENRE, PRICE_DESCRIPTION, PRICE_RENTFEE
FROM	MOVIE M, PRICE P
WHERE	M.PRICE_CODE = P.PRICE_CODE

--116
SELECT	MOVIE_GENRE, AVG(PRICE_RENTFEE) AS [AVERAGE RENTAL FEE]
FROM	MOVIE M, PRICE P
WHERE	M.PRICE_CODE = P.PRICE_CODE
GROUP BY MOVIE_GENRE

--117
SELECT	MOVIE_TITLE, (MOVIE_COST/PRICE_RENTFEE) AS [BREAKEVEN RENTALS]
FROM	MOVIE M, PRICE P
WHERE	M.PRICE_CODE = P.PRICE_CODE

--118
SELECT	MOVIE_TITLE, MOVIE_YEAR
FROM	MOVIE M, PRICE P
WHERE	M.PRICE_CODE = P.PRICE_CODE

--119
SELECT	MOVIE_TITLE, MOVIE_GENRE, MOVIE_COST
FROM	MOVIE M, PRICE P
WHERE	M.PRICE_CODE = P.PRICE_CODE AND
		MOVIE_COST BETWEEN 44.99 AND 49.99

--120
SELECT	MOVIE_TITLE, PRICE_DESCRIPTION, PRICE_RENTFEE, MOVIE_GENRE
FROM	MOVIE M, PRICE P
WHERE	M.PRICE_CODE = P.PRICE_CODE AND
		MOVIE_GENRE IN ('FAMILY','COMEDY','DRAMA')

--121
SELECT	MEM_NUM, MEM_FNAME, MEM_LNAME, MEM_BALANCE
FROM	MEMBERSHIP
WHERE	MEM_NUM IN (SELECT MEM_NUM FROM RENTAL)

--122
SELECT	MIN(MEM_BALANCE) AS [MINIMUM BALANCE], MAX(MEM_BALANCE) AS [MAXIMUM BALANCE], AVG(MEM_BALANCE) AS [AVERAGE BALANCE]
FROM	MEMBERSHIP
WHERE	MEM_NUM IN (SELECT MEM_NUM FROM RENTAL)

--123
SELECT	R.RENT_NUM, R.RENT_DATE, V.VID_NUM, M.MOVIE_TITLE, D.DETAIL_DUEDATE, D.DETAIL_RETURNDATE
FROM	RENTAL R, MOVIE M, DETAILRENTAL D, VIDEO V
WHERE	R.RENT_NUM = D.RENT_NUM AND
		D.VID_NUM = V.VID_NUM AND
		V.MOVIE_NUM = M.MOVIE_NUM AND
		D.DETAIL_RETURNDATE > D.DETAIL_DUEDATE
ORDER BY	R.RENT_NUM, R.RENT_DATE

--124
SELECT	R.RENT_NUM, R.RENT_DATE, M.MOVIE_TITLE, D.DETAIL_FEE
FROM	RENTAL R, MOVIE M, DETAILRENTAL D, VIDEO V
WHERE	R.RENT_NUM = D.RENT_NUM AND
		D.VID_NUM = V.VID_NUM AND
		V.MOVIE_NUM = M.MOVIE_NUM AND
		D.DETAIL_RETURNDATE <= D.DETAIL_DUEDATE

--125
SELECT	MOVIE_NUM, M.MOVIE_GENRE, AVGCOST AS [AVERAGE MOVIE COST], MOVIE_COST, (MOVIE_COST-AVGCOST)/AVGCOST * 100 AS [PERCENT DIFFERENCE]
FROM	MOVIE M,	(SELECT MOVIE_GENRE, AVG(MOVIE_COST) AS AVGCOST
					 FROM MOVIE
					GROUP BY MOVIE_GENRE) S
WHERE M.MOVIE_GENRE = S.MOVIE_GENRE
